# -*- coding: utf-8 -*-
"""Copy of emails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ll0u6b8lQYYoro6c5up-Ig5hc_L1yT8m
"""

import pandas as pd
phishing_keywords = ["urgent", "password reset", "bank", "verify", "account suspended"]

emails = pd.read_csv("/emails.csv")
if 'Content' in emails.columns:
  emails['is_phishing'] = emails['Content'].apply(
      lambda x: any(keyword in str(x).lower() for keyword in phishing_keywords)
  )
  emails.to_csv("/2409001204_phishing.csv", index=False)
  print("Phishing detection complete. ✅")
else:
  print("Error: The 'content' column is missing from the dataset.")

from google.colab import drive
drive.mount('/content/drive')